SherDashed/Controllers/AnnouncementController.cs
using Microsoft.AspNetCore.Mvc;
using SherDashed.Models.Announcement;
using SherDashed.Services;

namespace SherDashed.Controllers;

[Route("[controller]")]
public class AnnouncementController : Controller
{
    private readonly AnnouncementService _announcementService;

    public AnnouncementController(AnnouncementService announcementService)
    {
        _announcementService = announcementService;
    }
    
    // GET: /announcement
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var announcements = await _announcementService.GetAll();
        return View(announcements);
    }

    // GET: /announcement/details/{id}
    [HttpGet("details/{id:int}")]
    public async Task<IActionResult> Details(int id)
    {
        var announcement = await _announcementService.GetById(id);
        return announcement == null ? NotFound() : View(announcement);
    }
    
    // GET: /announcement/create
    [HttpGet("create")]
    public IActionResult Create()
    {
        var announcement = new Announcement
        {
            CreatedOn = DateTime.Now
        };
        return View(announcement);
    }

    // POST: /announcement/create
    [HttpPost("create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] Announcement announcement)
    {
        if (ModelState.IsValid)
        {
            await _announcementService.Add(announcement);
            return RedirectToAction(nameof(Index));
        }
        return View(announcement);
    }

    // GET: /announcement/edit/{id}
    [HttpGet("edit/{id:int}")]
    public async Task<IActionResult> Edit(int id)
    {
        var announcement = await _announcementService.GetById(id);
        return announcement == null ? NotFound() : View(announcement);
    }
    
    // POST: /announcement/edit/{id}
    [HttpPost("edit/{id:int}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [FromForm] Announcement announcement)
    {
        if (id != announcement.AnnouncementId)
            return BadRequest();

        if (ModelState.IsValid)
        {
            try
            {
                await _announcementService.Update(announcement);
                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException)
            {
                return NotFound();
            }
        }
        return View(announcement);
    }
    
    // POST: /announcement/delete/{id}
    [HttpPost("delete/{id:int}")]
    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _announcementService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        catch (InvalidOperationException)
        {
            return NotFound();
        }
    }
}

SherDashed/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SherDashed</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SherDashed.styles.css" asp-append-version="true"/>
</head>
<body class="bg-dark">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SherDashed</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Announcement" asp-action="Index">Announcement</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <main role="main" class="pb-3 text-muted">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted bg-dark">
    <div class="container">
        &copy; 2025 - SherDashed - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>